services:
  blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue
      - PORT=${PORT}
    ports:
      - "8081:${PORT}"
    networks:
      - app_network

  green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
      - PORT=${PORT}
    ports:
      - "8082:${PORT}"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - nginx-logs:/var/log/nginx
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT}
    command: >
      /bin/sh -c "
        if [ \"$ACTIVE_POOL\" = 'blue' ]; then
          export PRIMARY=app_blue; export BACKUP=app_green;
        else
          export PRIMARY=app_green; export BACKUP=app_blue;
        fi;
        envsubst '\$${PORT} \$${PRIMARY} \$${BACKUP}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
        nginx -t;
        nginx -g 'daemon off;'
      "
    depends_on:
      - green
      - blue
    networks:
      - app_network

  watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log_watcher
    volumes:
      - nginx-logs:/var/log/nginx
    env_file:
      - .env
    networks:
      - app_network

volumes:
  nginx-logs:

networks:
  app_network:
    driver: bridge
